import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ClientChrome from "./components/ClientChrome";
import { ThemeProvider } from "./providers/theme-provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Google Hackathon 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <ThemeProvider>
          <ClientChrome />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
